version: "2"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_docker
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME:root
      - MONGO_INITDB_ROOT_PASSWORD:rootpassword
    volumes:
      - ./data:/data/db:rw
    networks:
      - docker_network

networks:
  docker_network:
    external: true
